// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8kHnltvVHMRtQ6egKa3eP8yUqapXFBJo',
    appId: '1:1083352625174:web:ea007953f60ff6c151c537',
    messagingSenderId: '1083352625174',
    projectId: 'auth-uas-2025',
    authDomain: 'auth-uas-2025.firebaseapp.com',
    storageBucket: 'auth-uas-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBMP1OuB4zKWnArQAze1rNh714M1BtAng',
    appId: '1:1083352625174:android:d7aba8aa167aa5d051c537',
    messagingSenderId: '1083352625174',
    projectId: 'auth-uas-2025',
    storageBucket: 'auth-uas-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHQScceyvpRsxf1o2Yi0ch0bbmfL5YZko',
    appId: '1:1083352625174:ios:2a63a462c9ad645351c537',
    messagingSenderId: '1083352625174',
    projectId: 'auth-uas-2025',
    storageBucket: 'auth-uas-2025.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHQScceyvpRsxf1o2Yi0ch0bbmfL5YZko',
    appId: '1:1083352625174:ios:2a63a462c9ad645351c537',
    messagingSenderId: '1083352625174',
    projectId: 'auth-uas-2025',
    storageBucket: 'auth-uas-2025.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8kHnltvVHMRtQ6egKa3eP8yUqapXFBJo',
    appId: '1:1083352625174:web:5cd8597860866cf751c537',
    messagingSenderId: '1083352625174',
    projectId: 'auth-uas-2025',
    authDomain: 'auth-uas-2025.firebaseapp.com',
    storageBucket: 'auth-uas-2025.firebasestorage.app',
  );

}